name: Build GraalVM Java App with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up GraalVM 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: maven
    - name: Maybe install Graal
      run: ./install-graalvm.sh
    - name: Build with Maven
      run: mvn -s settings.xml -q clean package -Pnative -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
    - name: Copy artifacts to target
      run: |
        cp target/backend-proxy-1.0-SNAPSHOT-runner target/dist/application
        cp -R $GRAALVM_HOME/jre/lib/amd64 target/dist/lib
        cp $GRAALVM_HOME/jre/lib/security/cacerts target/dist/cacerts

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
